sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - php vendor/bin/coveralls -v
